name: Java CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read
  statuses: write
  checks: write

jobs:
  format:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        # Make sure the actual branch is checked out when running on pull requests
        ref: ${{ github.head_ref }}
        
    - name: Run prettier
      uses: creyD/prettier_action@v4.3
      with:
        prettier_plugins: prettier-plugin-java
        prettier_options: '--write **/*.java --tab-width 4'
        only_changed: true
   
  build:
    needs: format
    continue-on-error: true
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        codecov: [false]
        include:
        - os: ubuntu-latest
          codecov: true
        
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2.3.3
      with:
        arguments: desktop:dist
            
    - name: Test
      uses: gradle/gradle-build-action@v2.3.3
      with:
        arguments: tests:test
        
    - name: Report Test
      uses: dorny/test-reporter@v1.6.0
      if: always()
      with:
        name: "${{ matrix.os }} Test Report"
        path: tests/build/test-results/test/*.xml
        reporter: java-junit
        fail-on-error: true
        
    - name: Setup .NET Core # Required to execute ReportGenerator
      uses: actions/setup-dotnet@v3
      if: ${{ matrix.codecov && success()}}
      with:
        dotnet-version: 6.x
        dotnet-quality: 'ga'

    - name: ReportGenerator
      uses: danielpalme/ReportGenerator-GitHub-Action@5.1.17
      if: ${{ matrix.codecov && success()}}
      with:
        reports: tests/build/jacoco.xml
        targetdir: out
        reporttypes: MarkdownSummaryGithub
        
    - name: Publish Coverage Report
      uses: PavanMudigonda/markdown-reporter@v0.1
      if: ${{ matrix.codecov && success()}}
      with:
        markdown_path: out/SummaryGithub.md
        github_token: ${{ secrets.GITHUB_TOKEN }}
        report_name: Coverage Report
        report_title: Code Coverage Report
        
    - name: Upload game JAR
      uses: actions/upload-artifact@v3.1.2
      if: ${{ matrix.codecov && success()}}
      with:
        name: piazza-panic
        path: desktop/build/libs/desktop-1.0.jar
        
  checkstyle:
    needs: [format]
    if: ${{ false }}  # disable for now
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Run Checks
      uses: gradle/gradle-build-action@v2.3.3
      with:
        arguments: check
    
    - name: Add Checkstyle Report  
      uses: jwgmeligmeyling/checkstyle-github-action@master
      with:
        path: '**/reports/checkstyle/*.xml'
      
